version: '3.3'

services:
   db:
     image: mysql:5.7
     container_name: mysql_leantime
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

   web:
     build: .
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'host.docker.internal'
         LEAN_DB_USER: 'root'
         LEAN_DB_PASSWORD: 'admin'
         LEAN_DB_DATABASE: 'leantime'
     ports:
       - "80:80"
     depends_on:
       - db
     volumes:
       - .:/var/www/html

volumes:
    db_data: {}
